package itmo.utils.dto;

public enum SpaceMarineField {
    ID, NAME, COORDINATES_X, COORDINATES_Y, CREATION_DATE,
    HEALTH, CATEGORY, WEAPON_TYPE, MELEE_WEAPON, CHAPTER_NAME,
    CHAPTER_MARINES_COUNT
}
